test_01	: test_01.c ./../../obj/single_linked_list.o
	gcc -g -I./../../header test_01.c ./../../obj/single_linked_list.o -o test_01

./../../obj/single_linked_list.o : ./../../source/single_linked_list.c
	gcc -g -I./../../header -c ./../../source/single_linked_list.c -o ./../../obj/single_linked_list.o
